### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by liamxg** [wilkelab/influenza_pH1N1_timecourse#2]
<img width="861" alt="image" src="https://github.com/wilkelab/influenza_pH1N1_timecourse/assets/46078579/beacbc71-e167-4547-93e9-1887f9788ee7">

**Comment by liamxg** [comment]
Dear @clauswilke @ausmeyer,
Could you help me out, thanks.

**Comment by ausmeyer** [comment]
You just have to modify the script that is there. Assuming your path above is correct.

`
setwd('/HA/dNdS/distances/correlations
`
`
make.plot('HA')
`

Plot will appear...

`
ggsave(filename=paste('../correlations_violin_', protein, '.pdf', sep=''), height=5, width=15, useDingbats=F)
`

I tested it on my computer. Works fine. Here's the plot it made.

[correlations_violin_HA.pdf](https://github.com/wilkelab/influenza_pH1N1_timecourse/files/13654831/correlations_violin_HA.pdf)

**Comment by liamxg** [comment]
Dear @ausmeyer,
Thank you. solved.

BTW, how to calculate dNdS?

Is there any step by step tutorials, I also work on flu data, now, hope you can help me, thanks.

**Comment by ausmeyer** [comment]
To be honest, this is a surprisingly complicated question. There are several ways to calculate it but there is a lot of nuance and it would be worth delving more deeply into it with someone with some familiarity of the issues. There are issues applying these models to viruses (the models make assumptions about mutation fixation which may or may not be true in viruses early in outbreaks). There are issues selecting the model to fit (codon, nucleotide, protein). There are issues selecting the method of fitting. There are other issues of course.

These days you could just use datamonkey. I would probably just go with a FEL model as a first attempt. I would probably not estimate dS separately as you get started. 

https://www.datamonkey.org/fel

Otherwise, you could do it locally with HyPhy.

https://stevenweaver.github.io/hyphy-site/methods/selection-methods/

You could also do it with BEAST.

https://cran.r-project.org/web/packages/EvoPhylo/vignettes/rates-selection_BEAST2.html

I think MrBayes can do it. There are others like PaML, which I'm honestly not sure if people still use it or if it is maintained.

**Comment by liamxg** [comment]
Dear @ausmeyer,

I like your research very much, could you have a pipeline for this,  I want to use your pipeline for my datasets, thanks. I have a big flu dataset to analysis.
